# /etc/turnserver.conf
listening-port=3478
tls-listening-port=5349

fingerprint
lt-cred-mech

realm=79-76-127-159.nip.io

# Zakres portów relay (ważne dla WebRTC)
min-port=49152
max-port=65535

# Prosty user/pass na PoC
user=pocuser:pocpass

# Certy z certbota (nginx już je ma)
cert=/etc/letsencrypt/live/79-76-127-159.nip.io/fullchain.pem
pkey=/etc/letsencrypt/live/79-76-127-159.nip.io/privkey.pem

# Logi
verbose
log-file=/var/log/turnserver.log